
package dev.darsh.generatedStubs;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "StudentPortType", targetNamespace = "http://example.com/student")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns dev.darsh.generatedStubs.GetStudentResponse
     */
    @WebMethod(action = "getStudent")
    @WebResult(name = "GetStudentResponse", targetNamespace = "http://example.com/student", partName = "parameters")
    public GetStudentResponse getStudent(
        @WebParam(name = "GetStudentRequest", targetNamespace = "http://example.com/student", partName = "parameters")
        GetStudentRequest parameters);

}
