
package dev.darsh.generatedStubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "StudentService", targetNamespace = "http://example.com/student", wsdlLocation = "file:/D:/Learn/learnings/Spring-Boot/wsdl-to-java-stubs/src/main/resources/student-service.wsdl")
public class StudentService
    extends Service
{

    private static final URL STUDENTSERVICE_WSDL_LOCATION;
    private static final WebServiceException STUDENTSERVICE_EXCEPTION;
    private static final QName STUDENTSERVICE_QNAME = new QName("http://example.com/student", "StudentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Learn/learnings/Spring-Boot/wsdl-to-java-stubs/src/main/resources/student-service.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTSERVICE_WSDL_LOCATION = url;
        STUDENTSERVICE_EXCEPTION = e;
    }

    public StudentService() {
        super(__getWsdlLocation(), STUDENTSERVICE_QNAME);
    }

    public StudentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTSERVICE_QNAME, features);
    }

    public StudentService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTSERVICE_QNAME);
    }

    public StudentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTSERVICE_QNAME, features);
    }

    public StudentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentPortType
     */
    @WebEndpoint(name = "StudentPort")
    public StudentPortType getStudentPort() {
        return super.getPort(new QName("http://example.com/student", "StudentPort"), StudentPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentPortType
     */
    @WebEndpoint(name = "StudentPort")
    public StudentPortType getStudentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/student", "StudentPort"), StudentPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTSERVICE_EXCEPTION!= null) {
            throw STUDENTSERVICE_EXCEPTION;
        }
        return STUDENTSERVICE_WSDL_LOCATION;
    }

}
